version: '3.5'
services:
  api:
    build: ./dotnetmicroservice
    depends_on:
      - db
    ports:
      - 80:80
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: onlyfordev
    volumes:
      - ./data/sql-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
