// <auto-generated />
using dotnetmicroservice;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace dotnetmicroservice.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20201210142935_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("EFGetStarted.Robot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("positionX")
                        .HasColumnType("integer");

                    b.Property<int>("positionY")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Robots");
                });
#pragma warning restore 612, 618
        }
    }
}
